# Generated by Django 3.2.8 on 2021-10-13 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, choices=[('01', 'Adm'), ('15', 'Comercial'), ('30', 'RH')], max_length=2, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='certificado',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='certificado',
            name='groups',
        ),
        migrations.AddField(
            model_name='certificado',
            name='groups',
            field=models.ManyToManyField(to='core.Group'),
        ),
    ]
