# Generated by Django 3.2.8 on 2021-10-13 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211013_0102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='codigo',
        ),
        migrations.AddField(
            model_name='group',
            name='cod',
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
