# Generated by Django 3.2.8 on 2021-10-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20211013_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='username',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='group',
            name='cod',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
